// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAgHVCFP6R-uoY49EccuZhPtVoEhjU40',
    appId: '1:375762163417:web:64e1ec057ddbbf239fd0c8',
    messagingSenderId: '375762163417',
    projectId: 'honoursproject-4100c',
    authDomain: 'honoursproject-4100c.firebaseapp.com',
    storageBucket: 'honoursproject-4100c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCSsqK0BQ9PbP_j1CcS63WYn57s0c_prU',
    appId: '1:375762163417:android:f19a5f0bc9bcd6d59fd0c8',
    messagingSenderId: '375762163417',
    projectId: 'honoursproject-4100c',
    storageBucket: 'honoursproject-4100c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc2r3-kyci9D7m_U9pABlXljaq7pu1FDQ',
    appId: '1:375762163417:ios:d027de05c76d50239fd0c8',
    messagingSenderId: '375762163417',
    projectId: 'honoursproject-4100c',
    storageBucket: 'honoursproject-4100c.firebasestorage.app',
    iosBundleId: 'com.example.honoursProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc2r3-kyci9D7m_U9pABlXljaq7pu1FDQ',
    appId: '1:375762163417:ios:d027de05c76d50239fd0c8',
    messagingSenderId: '375762163417',
    projectId: 'honoursproject-4100c',
    storageBucket: 'honoursproject-4100c.firebasestorage.app',
    iosBundleId: 'com.example.honoursProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAAgHVCFP6R-uoY49EccuZhPtVoEhjU40',
    appId: '1:375762163417:web:dde28950f13e9a929fd0c8',
    messagingSenderId: '375762163417',
    projectId: 'honoursproject-4100c',
    authDomain: 'honoursproject-4100c.firebaseapp.com',
    storageBucket: 'honoursproject-4100c.firebasestorage.app',
  );
}
